All:Date.o User.o Meeting.o MeetingManage.o UserManage.o
Date.o: Date.h Date.cpp
	g++ -c Date.cpp
User.o: User.h User.cpp
	g++ -c User.cpp
Meeting.o: Meeting.h Meeting.cpp
	g++ -c Meeting.cpp
MeetingManage.o: MeetingManage.h MeetingManage.cpp
	g++ -c MeetingManage.cpp
UserManage.o: UserManage.h UserManage.cpp
	g++ -c UserManage.cpp
